### ISSUE TITLE
NaN vs. 0

### ISSUE THREAD

**Issue by shrez28** [lmarusich/rmcorr#16]
I am using the rmcorr_mat function.
For few correlations it returns NaN and for few 0
When would rmcorr_mat return NaN/0 ?
Can NaN be replaced as 0?

Thanks you!
Shrez

**Comment by jbakdash** [comment]
Hi Shrez,

Are you comfortable sharing part of the data (assuming it's de-identified) with some of the variables where these issues occur? Feel free to take this offline: jbakdash@gmail.com and Laura's email: lmarusich@gmail.com

My guess is maybe complete missing data for some variables with the NANs. But it's also possible there's a bug. Or both. 

Thanks,
Jon

**Comment by jbakdash** [comment]
To document, the NaN issue was occuring because the same value was repeated in the data often (i.e., not enough variablility). One way to address this is to create variability by adding a small amount of random noise with a mean of zero to each variable with the frequent repeated values.
