### ISSUE TITLE
Extracting intercept for each participant

### ISSUE THREAD

**Issue by omian** [lmarusich/rmcorr#20]
Thank you for releasing this useful package!

I'm trying to extract the extract the common slope as well as the individual intercepts so that I can create plots outside of R.

Referring to the example at the link below, I can see how to access the common slope as well as a series of intercepts. However I don't understand why no intercept is given for the final participant (participant 8 in the example). Could you please clarify?

Thanks

Example link: https://lmarusich.github.io/rmcorr/articles/FAQ_and_limitations.html#how-to-extract-the-slope-and-its-confidence-interval

**Comment by lmarusich** [comment]
Thanks for the message! There is an overall intercept in the model, and the intercepts for the participants are interpreted in reference to that overall value. In the referenced example, the intercept you would use for plotting would be the overall intercept of 7.66 + each individual’s coefficient (0 for for Participant 8).

**Comment by omian** [comment]
Thanks. I thought that might be the case, but alongside this I also expected that individual simple linear regression between my.rmc$model$model$Measure1 and my.rmc$model$fitted.values for each participant would give a matching intercept for that participant. It does match for Participants 1 to 7, but does not match for Participant 8 (using an 0 offset for Participant 8).

Code:

```
df <- my.rmc$model$model
df$fitted <- c(my.rmc$model$fitted.values)

for (p in 1:8) {
  
  # Intercept for current participant, obtained from rmcorr coefficients list
  if (p == 8) { 
    intercept_offset <- 0
  }else{
    intercept_offset <- my.rmc$model$coefficients[[paste("Participant",p,sep="")]]
  }
  intercept_from_rmcorr_coefficients <- my.rmc$model$coefficients[["(Intercept)"]] + intercept_offset
  
  # Intercept for current participant, obtained via simple linear regression between Measure1 and rmcorr fitted values
  participant_fitted_lm <- lm(fitted ~ Measure1, data =  subset(df, Participant == p))
  intercept_from_rmcorr_fitted_values <- participant_fitted_lm$coefficients[["(Intercept)"]]
  
  # Summarise in console
  print(paste("Participant ",p," intercept:",
              " From rmcorr coefficients = ",  round(intercept_from_rmcorr_coefficients, digits=4),
              "; From rmcorr fitted values = ", round(intercept_from_rmcorr_fitted_values, digits=4),
              sep=""))
}
```

Output:

```
[1] "Participant 1 intercept: From rmcorr coefficients = 6.9299; From rmcorr fitted values = 6.9299"
[1] "Participant 2 intercept: From rmcorr coefficients = 7.6345; From rmcorr fitted values = 7.6345"
[1] "Participant 3 intercept: From rmcorr coefficients = 7.8799; From rmcorr fitted values = 7.8799"
[1] "Participant 4 intercept: From rmcorr coefficients = 7.9014; From rmcorr fitted values = 7.9014"
[1] "Participant 5 intercept: From rmcorr coefficients = 7.7902; From rmcorr fitted values = 7.7902"
[1] "Participant 6 intercept: From rmcorr coefficients = 7.8563; From rmcorr fitted values = 7.8563"
[1] "Participant 7 intercept: From rmcorr coefficients = 7.622; From rmcorr fitted values = 7.622"
[1] "Participant 8 intercept: From rmcorr coefficients = 7.6559; From rmcorr fitted values = 7.6332"
```

Note discrepancy for Participant 8.

Is my expectation wrong here?

**Comment by lmarusich** [comment]
Oops, you're right - it's not as simple as I was thinking. Because of the contrasts being used, you would actually need to subtract the coefficients of Participants 1 through 7 from the overall intercept to get the effective intercept for Participant 8.

`my.rmc$model$coefficients[1] - sum(my.rmc$model$coefficients[2:8])`

`(Intercept) 
    7.63319 `

**Comment by omian** [comment]
Thanks for clarifying!

I'm now curious as to why the sum of the participant 1-7 coefficients need to be **subtracted** from the overall intercept to get effective intercept for participant 8, when for the other participants the participant coefficients need to be **added** to the overall intercept. Would you mind explaining or pointing me in the direction of what to read to understand this?

**Comment by jbakdash** [comment]
These are insightful and suprisingly challenging questions.

Rmcorr relies uses effect coding. Thanks to @lmarusich for clarifying this. I had it wrong in my initial response. This complicated stuff! 

- There are details about unweighted effect coding in Cohen et al. (2013), Applied Multiple Regression/Correlation Analysis for the Behavioral Sciences chapter 8: [Cohen book](https://books.google.com/books?id=fAnSOgbdFXIC&newbks=1&newbks_redir=0&lpg=PP1&dq=cohen%20applied%20statistics&pg=PT311#v=onepage&q&f=false)

-  _model_matrix()_  can be used to view the coding behind the scences:
`my.rmc <- rmcorr(participant = Subject, measure1 = PaCO2, measure2 = pH, 
                 dataset = bland1995)`
`mm.my.rmc <- model.matrix(my.rmc$model)`
`mm.my.rmc ` 

I hope this addresses your questions.

**Comment by omian** [comment]
@jbakdash Thanks! 

I'll take a look at that book chapter, and that model.matrix function looks handy.
