### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by JumperSVK** [lmarusich/rmcorr#21]
Hello, I am trying to use rmcorr package in Rstudio with my data, but iam getting error messsage constatantly, where is the problem? Thank you for help.

My data consists of 121 participants, i have 2 measures for each participant before and after intervention.

> dim(Skuska)
[1] 121   3

> head(Skuska)
# A tibble: 6 × 3
    kod RMSDD_pred RMSDD_po
  <dbl>      <dbl>    <dbl>
1     1      164.      26.9
2     2       25.4     33.4
3     3      148.      47.6
4     4      208.     175. 
5     5       18.2     31.6
6     6       33       93.9
....

> rmcorr(kod, Skuska$RMSDD_pred, Skuska$RMSDD_po, Skuska, CI.level = 0.95, CIs = ("analytic"), nreps = 100, bstrap.out = F)
Error in psych::r.con(rmcorrvalue, errordf + 2, p = CI.level) : 
  number of subjects must be greater than 3
In addition: Warning messages:
1: In rmcorr(kod, Skuska$RMSDD_pred, Skuska$RMSDD_po, Skuska, CI.level = 0.95,  :
  'kod' coerced into a factor
2: attempting model selection on an essentially perfect fit is nonsense

**Comment by lmarusich** [comment]
Hello, I think the problem is that you only have one row per participant. In order to use repeated measures correlation, you would need repeated observations of both variables (i.e., more than one row for each participant).

**Comment by JumperSVK** [comment]
Ok, thank you for answer.
