### ISSUE TITLE
Don't change or revert options

### ISSUE THREAD

**Issue by svenhalvorson** [lmarusich/rmcorr#3]
Hi there,

I had a huge headache today that was caused by the rmcorr function changing the contrast options and then giving me unexpected results from subsequent models. In general, I don't think this is a good programming practice.

The current options could be saved and reverted at the end of the function? Or the proper contrasts applied directly?

Thanks for the library and interesting paper!

**Comment by lmarusich** [comment]
Are you using a recent version of the package? As of 0.3.0, the contrasts should revert back to what they were.

**Comment by lmarusich** [comment]
Are you using a recent version of the package? As of 0.4.0, the contrasts should revert back to what they were.

**Comment by svenhalvorson** [comment]
Ope, guess not. That should probably have been step one! Sorry
