### ISSUE TITLE
Error in isa(Participant, "character") : There is no "isa" function

### ISSUE THREAD

**Issue by limohulb** [lmarusich/rmcorr#9]
Hi, Dr. Laura R. Marusich
I have this problem when running the latest version of rmcprr, can you please help me with this.

library(rmcorr)
rmcorr(Subject, PaCO2, pH, bland1995)
Error in isa(Participant, "character") : There is no "isa" function

**Comment by lmarusich** [comment]
Thanks for the message - can you tell us what version of R you're running? This error has been popping up occasionally, but updating R seems to solve it.

**Comment by jbakdash** [comment]
Starting with rmcorr 0.5.2, R 4.1.0 is now required. This wasn't documented previously. Sorry, for the error
